name: eq-analysis

services:
  source_postgres:
    image: postgres:15
    ports:
      - 5433:5432
    networks:
      - eq_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  bi_postgres:
    image: postgres:15
    ports:
      - 5434:5432
    networks:
      - eq_network
    environment:
      POSTGRES_DB: bi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  elt_script:
    build:
      context: ./elt_script # Directory containing the Dockerfile and elt_script.py
      dockerfile: Dockerfile # Name of the Dockerfile, if it's something other than "Dockerfile", specify here
    command: [ "python", "elt_script.py" ]
    networks:
      - eq_network
    depends_on:
      - source_postgres
      - bi_postgres

networks:
  eq_network:
    driver: bridge

  