CREATE TABLE earthquakes (
    id SERIAL PRIMARY KEY,
    place TEXT,
    mag NUMERIC,
    time BIGINT,
    updated BIGINT,
    tz INTEGER,
    url TEXT,
    detail TEXT,
    felt INTEGER,
    cdi NUMERIC,
    mmi NUMERIC,
    alert TEXT,
    status TEXT,
    tsunami INTEGER,
    sig INTEGER,
    net TEXT,
    code TEXT,
    ids TEXT,
    sources TEXT,
    types TEXT,
    nst INTEGER,
    dmin NUMERIC,
    rms NUMERIC,
    gap NUMERIC,
    magType TEXT,
    type TEXT,
    title TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);